### ISSUE TITLE
error when execute latexdiff

### ISSUE THREAD

**Issue by rototrolxtrol** [driquet/rcs-latexdiff#9]
I execute (@ svn repository), 
_rcs-latexdiff -v Main.tex r82 r85_

and get this error:
 
_...
Execute latexdiff
Traceback (most recent call last):
  File "/usr/local/bin/rcs-latexdiff", line 9, in <module>
    load_entry_point('rcs-latexdiff==1.0', 'console_scripts', 'rcs-latexdiff')()
  File "build/bdist.macosx-10.10-x86_64/egg/rcs_latexdiff/rcs_latexdiff.py", line 385, in main
  File "build/bdist.macosx-10.10-x86_64/egg/rcs_latexdiff/rcs_latexdiff.py", line 105, in exec_latexmk
OSError: [Errno 2] No such file or directory: ''_

I run the command _latexdiff_ passing the generated files  (diff.tex.new and diff.tex.old) and get the pdf as expected.

Do you know how to fix this issue? Thanks in advance for this tool.

**Comment by ihincks** [comment]
This is happening on line 105 of rcs_latexdiff.py for the code `os.chdir(src_path)` and I think the problem might be that the `src_path` string is empty. I will submit a pull request shortly that I think will fix this problem...

**Comment by ihincks** [comment]
Until the pull request goes through you can try installing my branch chdir-bug-fix to see if it actually fixes your error

**Comment by rototrolxtrol** [comment]
It fixed the error. Thanks !!

**Comment by driquet** [comment]
Fixed by @ihincks !
Many thanks for that !

**Comment by driquet** [comment]
Fixed by @ihincks !
Many thanks for that !
